server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: building
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Building;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        generate_statistics: false
springdoc:
  swagger-ui:
    path: /test-docs
